cosmiccompanion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
from .views import apod
from django.urls import path

urlpatterns = [
    path('', views.apod, name='home'),
    path('about/', views.about, name='about'),
    path('events/', views.events_index, name='events_index'),
    path('events/<int:event_id>/', views.events_detail, name='events_detail'),
    path('events/create/', views.EventCreate.as_view(), name='events_create'),
    path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='events_update'),
    path('events/<int:pk>/delete/', views.EventDelete.as_view(), name='events_delete'),
    path('events/<int:event_id>/add_photo/', views.add_photo, name='add_photo'),
    path('events/<int:event_id>/remove_photo/<int:photo_id>/', views.remove_photo, name='remove_photo'),
    path('events/<int:event_id>/assoc_event/<int:celestialobject_id>', views.assoc_celestialobject, name='assoc_celestialobject'),
    path('events/<int:event_id>/disassoc_event/<int:celestialobject_id>', views.disassoc_celestialobject, name='disassoc_celestialobject'),
    path('celestialobjects/', views.CelestialObjectList.as_view(), name='celestial_objects_index'),
    path('celestialobjects/<int:pk>/', views.CelestialObjectDetail.as_view(), name='celestial_objects_detail'),
    path('celestialobjects/create/', views.CelestialObjectCreate.as_view(), name='celestial_objects_create'),
    path('celestialobjects/<int:pk>/update/', views.CelestialObjectUpdate.as_view(), name='celestial_objects_update'),
    path('celestialobjects/<int:pk>/delete', views.CelestialObjectDelete.as_view(), name='celestial_objects_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('apod/', apod, name='apod'),
    
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date, time
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class CelestialObject(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=5000)
    last_appearance = models.DateField()
    discovered_by = models.CharField(max_length=250)
    age = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('celestial_objects_detail', kwargs={'pk': self.id})
    
    class Meta:
        ordering = ['name']


class Event(models.Model):
    name = models.CharField(max_length=250)
    date = models.DateField()
    time = models.TimeField()
    description = models.TextField(max_length=5000)
    celestial_objects = models.ManyToManyField(CelestialObject)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({self.id})'

    def get_absolute_url(self):
        return reverse('events_detail', kwargs={'event_id': self.id})
    
    class Meta:
        ordering = ['date']


class Photo(models.Model):
    url = models.CharField(max_length=250)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for event_id: {self.event_id} @{self.url}"

    

main_app/forms.py
from django import forms
from .models import Event
from .models import CelestialObject


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'date', 'time', 'description', 'celestial_objects']
    def __init__(self, *args, **kwargs): 
      super().__init__(*args, **kwargs) 
      celestialobjects = CelestialObject.objects.all()
      choices = [(celestialobject.id, celestialobject.name) for celestialobject in celestialobjects]
      self.fields['celestial_objects'].widget = forms.SelectMultiple(choices=choices)
      
      
class CelestialObjectForm(forms.ModelForm):
    class Meta:
        model = CelestialObject
        fields = ['name', 'description', 'last_appearance', 'discovered_by', 'age']
    def __init__(self, *args, **kwargs):
      super().__init__(*args, **kwargs)
    #   events1 = Event.objects.all()
    #   choices = [(event.id, event.name) for event in events1]
    #   self.fields['events'].widget = forms.SelectMultiple(choices=choices)


class DateRangeForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Event, CelestialObject, Photo
from .forms import EventForm
from .forms import CelestialObjectForm
from .forms import DateRangeForm
import requests
from datetime import datetime
import pytz


# Create your views here.
def apod(request):
    api_key = 'JEY9zPlHaKd05eOsx447DLTJu2n51dv8TMBNZc4a'
    pacific_tz = pytz.timezone('US/Pacific')
    # today = '2023-02-09'
    today = datetime.now(pacific_tz).date()
    url = f'https://api.nasa.gov/planetary/apod?date={today}&api_key={api_key}'
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        context = {
            'title': data['title'],
            'date': data['date'],
            'explanation': data['explanation'],
            'image_url': data['hdurl'],
        }
        print("!!!!!!!!!!!!", context)
        return render(request, 'home.html', context)
        
    else:
        return render(request, 'error.html', {'error': 'Failed to retrieve APOD.'})


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html') 


def events_index(request):
    events = Event.objects.all()
    form = DateRangeForm(request.GET)
    if form.is_valid():
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']
        events = events.filter(date__range=(start_date, end_date))
    return render(request, 'events/index.html', { 'events': events, 'form': form })

def events_detail(request, event_id):
    event = Event.objects.get(id=event_id)
    return render(request, 'events/detail.html', { 'event': event })
    
class EventCreate(LoginRequiredMixin, CreateView):
  model = Event
  form_class = EventForm
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  
  
class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm
    
    def form_valid(self, form):
        event = form.save(commit=False)
        if event.user !=self.request.user:
            return redirect("/events/")
        return super().form_valid(form)
    
    
    # def dispatch(self, request, *args, **kwargs):
    #     event = self.get_object()
    #     if event.user != self.request.user:
    #         return redirect("/events/")
    #     return super().dispatch(request, *args, **kwargs)

class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = '/events/'

class CelestialObjectList(ListView):
    model = CelestialObject

class CelestialObjectDetail(DetailView):
    model = CelestialObject
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        celestial_object = self.object
        events = celestial_object.event_set.all()
        context['events'] = events
        return context

class CelestialObjectCreate(LoginRequiredMixin, CreateView):
    model = CelestialObject
    form_class = CelestialObjectForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CelestialObjectUpdate(LoginRequiredMixin, UpdateView):
    model = CelestialObject
    form_class = CelestialObjectForm
    def form_valid(self, form):
        celestialobject = form.save(commit=False)
        if celestialobject.user !=self.request.user:
            return redirect("/celestialevents/")
        return super().form_valid(form)

class CelestialObjectDelete(LoginRequiredMixin, DeleteView):
    model = CelestialObject
    success_url = '/celestialobjects/'

@login_required
def assoc_celestialobject(request, event_id, celestialobject_id):
    Event.objects.get(id=event_id).celestialobjects.add(celestialobject_id)
    return redirect('events_detail', event_id=event_id)

@login_required
def disassoc_celestialobject(request, event_id, celestialobject_id):
    Event.objects.get(id=event_id).celestialobjects.remove(celestialobject_id)
    return redirect('events_detail', event_id=event_id)




def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('/')
    else:
      error_message = 'Invalid sign up - try again'

  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def add_photo(request, event_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, event_id=event_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('events_detail', event_id=event_id)


@login_required
def remove_photo(request, event_id, photo_id):
    photo = Photo.objects.get(id=photo_id)
    if photo.event.user != request.user:
        return HttpResponseForbidden("You do not have permission to delete this photo.")
    s3 = boto3.client('s3')
    key = photo.url.split("/")[-1]
    bucket = os.environ['S3_BUCKET']
    s3.delete_object(Bucket=bucket, Key=key)
    photo.delete()
    event = Event.objects.get(id=event_id)
    return redirect('events_detail', event_id=photo.event.id)

main_app/templates/events/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="card" style="color: white; background-image: url(https://i.imgur.com/Bl8jv0P.png);">
  <div class="card-content" style="color: white; background-image: url(https://i.imgur.com/Bl8jv0P.png);">
    <h3>{{ event.name }}</h3>
    <p>Date - {{ event.date }}</p>   
    <p>Time - {{ event.time }}</p>
    <p>Description - {{ event.description }}</p>
  </div>
  <div class="card-content" style="color: white; background-image: url(https://i.imgur.com/Bl8jv0P.png);">
    <p>Related Celestial Objects:</p>
    {% for celestial_object in event.celestial_objects.all %}
      <li><a href=" {% url 'celestial_objects_detail' celestial_object.id %} "> {{ celestial_object.name }}</a></li>
    {% endfor %}
  </div>
  <div class="card-action" style="color: white; background-image: url(https://i.imgur.com/Bl8jv0P.png);">
    {% if user.is_authenticated %}
      {% if user.id == event.user.id %}
    <a href="{% url 'events_update' event.id %}">Edit</a>
    <a href="{% url 'events_delete' event.id %}">Delete</a>
      {% else %}
        <p></p>
      {% endif %}
    {% endif %}
  </div>

  {% for photo in event.photo_set.all %}

  <img class="responsive-img card-panel" src="{{photo.url}}" style="color: white; background-image: url(https://i.imgur.com/Bl8jv0P.png);">
  {% if user.is_authenticated %}
    <form action="{% url 'remove_photo' event.id photo.id %}" method="POST" style="background-image: url(https://i.imgur.com/Bl8jv0P.png);">
      {% csrf_token %}
      {% if user.id == event.user.id %}
        <button type="submit" class="btn-delete">Delete Photo</button>
      {% endif %}
    </form>
  {% endif %}
{% empty %}
  <div class="card-panel red-text center-align" style="color: white; background-image: url(https://i.imgur.com/Bl8jv0P.png);">No Photos Uploaded</div>
{% endfor %}
  {% if user.is_authenticated %}
      {% if user.id == event.user.id %}

    <form action="{% url 'add_photo' event.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <label for="file-upload" class="custom-file-upload">
        Choose Photo
      </label>
      <input id="file-upload" type="file" name="photo-file" />
      <br><br>
      <button type="submit" class="btn">Upload Photo</button>
    </form>
    
  {% else %}
        <p></p>
      {% endif %}
    {% endif %}
</div>

{% endblock %}

main_app/templates/events/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Celestial Events</h1>

<div class="filter-form"> 
  <p>Filter events by date:</p>
  <form method="get" class="filter-table">
    {{ form.as_table }}
    <button type="submit" class="btn">Filter</button>
  </form>
</div>


{% for event in events %}
  <div class="card">
    <a href="{% url 'events_detail' event.id %}">
        <div class="card-content">
            <span class="card-title">{{ event.name }}</span>
            <p>Date - {{ event.date }}</p>   
            <p>Time - {{ event.time }}</p>   
            <p>Description - {{ event.description }}</p>
            <!-- <p>User - {{ event.user }}</p> -->
            <ul>Celestial Objects:
                {% for celestial_object in event.celestial_objects.all %}
                  <li>{{ celestial_object.name }}</li>
                {% endfor %}
            </ul>
        </div>
    </a>
  </div>
{% empty %}
  <li> No events found for this date range.</li>
{% endfor %}

<script>
  const startDateEl = document.getElementById('id_start_date');
  M.Datepicker.init(startDateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const endDateEl = document.getElementById('id_end_date');
  M.Datepicker.init(endDateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

</script>

{% endblock %}